### ISSUE TITLE
Clean up build options

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudioApplication#18]
We want to clean up the build options to make things easier on future maintainers.  The options should be about the app, I don't think there are good reasons to customize the OpenStudio Core build.  OpenStudio Core should just build with its default settings.  The following options can be removed from the app

```
BUILD_DOCUMENTATION - NA
BUILD_DVIEW - NA
BUILD_JAVA_BINDINGS - NA
BUILD_NUGET_PACKAGE - NA
BUILD_OS_APP - always true
BUILD_PAT - NA
BUILD_PYTHON_BINDINGS - NA
BUILD_SHARED_LIBS - NA
BUILD_V8_BINDINGS - NA
```

I don't think anyone is using our ModelEditor C# bindings so `BUILD_CSHARP_BINDINGS` can be removed, might leave it (default to off) in but mark as advanced.

The following options can stay
```
BUILD_TESTING:BOOL=ON
BUILD_WITH_MULTIPLE_PROCESSES:BOOL=ON
BUILD_PACKAGE:BOOL=ON
```

**Comment by tijcolem** [comment]
Unused build options for the App have been removed.
