### ISSUE TITLE
Add github pages CI 

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudioApplication#32]
Add docs folder and port some content over from https://github.com/NREL/OpenStudio-user-documentation/ (https://nrel.github.io/OpenStudio-user-documentation/) (include a few markdown files and images, etc).  Add CI task to make docs and post to github pages on merge to master

**Comment by tijcolem** [comment]
This now has GitHub pages activated for OpenStudioApplication user docs. 
https://nrel.github.io/OpenStudioApplication/
A couple of notes on this. 

1. branch `gh-pages-markdown` contain the markdown content. 
2. branch `gh-pages` contain the converted html via mkdocs (v0.11.1). 

To enable the automatic markdown build by GitHub,  the markdown contents need to be compatible with GitHub Jekyll markdown.  For now, the steps to build are to covert the markdown contents `gh-pages-markdown` to html using mkdocs (v0.11.1) and commit the html to `gh-pages` branch.
