### ISSUE TITLE
Purge Button within Shading sub-tab of Facility tab won't execute

### ISSUE THREAD

**Issue by eomere** [NREL/OpenStudioApplication#77]
Issue overview
--------------
The purge button within the Shading sub-tab of the Facility tab won't execute. This issue cuts across all Operating Systems (Windows, Mac, Ubuntu). 

## Current Behavior
None of the created shading surface groups are removed. 

## Expected Behavior
This button should remove any shading surface groups that are not used within the model.

## Steps to Reproduce
1. Launch the OpenStudio App (no need to open any previously generated model)
2. Go to the Facility tab
3. Go to the Shading tab
4. Click the "Green" button to create new shading surface groups
5. Click the Purge Button to remove these shading surface groups 

## Possible Solution
There are two possible solutions. The first is to make the purge button execute. The second is to make the purge button uninteractive (color grey, as opposed to color red). The required solution depends on the expected functionality within this tab.

**Comment by jmarrec** [comment]
I think the real question is what would you expect to happen? If you have shading in your model, it is supposed to be used by definition. This isn't like constructions which should be referenced by something else to be actually used.

Making the button inactive is an option is you agree with the above.

**Comment by jmarrec** [comment]
Actually, let me look into it a bit more. I think we could at least purge the Shading Surface Groups if they have zero surfaces in there?

**Comment by jmarrec** [comment]
Actually it does execute just fine.

![image](https://user-images.githubusercontent.com/5479063/76771237-54e55c80-679f-11ea-9026-9db4d4975326.png)

Click on purge:

![image](https://user-images.githubusercontent.com/5479063/76771258-5f9ff180-679f-11ea-8842-1af8975f99c5.png)

https://github.com/NREL/OpenStudioApplication/blob/38dd2b437fa7da76ef44528bf7a4c256b39ae33b/src/openstudio_lib/FacilityShadingGridView.cpp#L424-L429

**Comment by jmarrec** [comment]
I think it would make more sense to delete shading surface groups which have no surfaces instead. One could select all and click the delete button to remove everything anyways.
